#!/usr/bin/env python
from ErocoolAPI.api import ErocoolAPI
import argparse, sys

parser = argparse.ArgumentParser(description='ErocoolAPI Commandline tool')

parser.add_argument('url', help = 'URL of the contents')
parser.add_argument('-s', '--start', type = int, default = 1, help = 'Specify the first page number to start downloading.')
parser.add_argument('-e', '--end', type = int, help='Specify the last page number to finish downloading.')
parser.add_argument('-o', '--output', help='Output directory')
parser.add_argument('-n', '--name', help= 'Directory name')

args = parser.parse_args()

site = ErocoolAPI.set(args.url)
site.async_download(absolute_path = args.output, directory_name = args.name, start = args.start, end = args.end)
sys.exit()